export const DO_LOGIN_INIT = "DO_LOGIN_INIT";
export const DO_LOGIN_INIT_SUCCESS = "DO_LOGIN_INIT_SUCCESS";
export const DO_LOGIN_SUBMIT = "DO_LOGIN_SUBMIT";
export const DO_LOGIN_SUBMIT_SUCCESS = "DO_LOGIN_SUBMIT_SUCCESS";
export const DO_LOGOUT = "DO_LOGOUT";
export const DO_LOGOUT_SUCCESS = "DO_LOGOUT_SUCCESS";